/* Autogenerated file. Do not edit manually. */
export type { DVFDepositContract } from './DVFDepositContract'
export * as factories from './factories'
export { DVFDepositContract__factory } from './factories/DVFDepositContract__factory'
